### ISSUE TITLE
consistency issue in the vietnamese accents

### ISSUE THREAD

**Issue by RosaWagner** [rubjo/victor-mono-font#2]
For `circumflex_acute` `circumflex_hookabove` and `circumflex_grave`, you can choose to either put above or aside, but should be the same for lowercases and capitals. The other accents stacks above each other.

<img width="1246" alt="Capture d’écran 2023-06-15 à 13 08 53" src="https://github.com/rubjo/victor-mono-font/assets/12222436/284161fb-ee17-431e-9df4-f35c5a47f552">

**Comment by rubjo** [comment]
Fixed :)
