### ISSUE TITLE
Rename master Light into "Thin" and master Light Italic into "Thin Italic"

### ISSUE THREAD

**Issue by RosaWagner** [rubjo/victor-mono-font#3]
in order to fix this fail:

* 🔥 **FAIL** 'Thin Italic' instance has the same coordinates as the default instance; its subfamily name should be 'Light Italic'

The wording is a bit wrong; it means, the default master is the one with coordinate 50, which correspond to the Thin instance; they should have the same name.

**Comment by rubjo** [comment]
I didn't even get that fail, but fixed now 👍🏻
