### ISSUE TITLE
soft dotted in fixed in Roman but not in italic

### ISSUE THREAD

**Issue by RosaWagner** [rubjo/victor-mono-font#4]
Somehow you fixed the soft dotted feature in the upright font ;)
In the italic, you just need to add a top anchor to `dotless i`, `dotless j` and update/compile the features.

**Comment by rubjo** [comment]
This is weird.
- I'm still getting the soft dot fail for both upright and italic. There must be some differences in the test setups somewhere.
- Both `dotless i` and `dotless j` had top anchors everywhere, and after an update/recompile a git diff showed no changes.

I did some other changes, so maybe it's OK now, I don't know :)

**Comment by RosaWagner** [comment]
ok let's roll then, tell me when there is a new release

**Comment by rubjo** [comment]
As in I should make a new release before you go further? The current release has the most recent binaries uploaded manually. Maybe I need to do a new release with a new tag in order for the binaries to be automatically attached?

**Comment by RosaWagner** [comment]
I don't know, but you can try :) Tell me if it works, I never tried this feature of the ghaction.

**Comment by rubjo** [comment]
Yep, bumping the release version by 0.001 worked: action auto-attached new binaries.
