### ISSUE TITLE
Add OFL.txt and Description.html in release

### ISSUE THREAD

**Issue by RosaWagner** [rubjo/victor-mono-font#5]

**Comment by rubjo** [comment]
What, like attach them manually to the release files?

**Comment by RosaWagner** [comment]
I guess so. It's a bit curious the ghaction doesn't do it. Something to fix on https://github.com/googlefonts/googlefonts-project-template side.

**Comment by rubjo** [comment]
done :)

**Comment by RosaWagner** [comment]
Could it be in the same zip as the fonts? 😬 sorry sorry usually I do that part manually myself

**Comment by rubjo** [comment]
Aaah all your rules Rosa :P No problem, fixed.

**Comment by RosaWagner** [comment]
somehow the license has a .html suffix which creates problems

**Comment by rubjo** [comment]
Hm yes, was a bit quick there. Both extra files should be in the correct format now.
